services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_RESULTS_QUEUE: ${RABBITMQ_RESULTS_QUEUE}

  parser:
    build:
      context: ./app
    container_name: ${PARSER_ID}
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_RESULTS_QUEUE: ${RABBITMQ_RESULTS_QUEUE}
      QUEUE_NAME: ${QUEUE_NAME}
      STATE: ${STATE}
      PARSER_ID: ${PARSER_ID}
